### ISSUE TITLE
[SCRUM] 200617

### ISSUE THREAD

**Issue by beemiel** [codesquad-member-2020/issue-tracker-06#24]
- 어제 한 일
  필터 쬐끔 하다가 놀았습니다🙏
- 오늘 할 일
  양심적으로 필터하기
- 컨디션
   열심히 놀았더니 조금 피곤
- 추가 사항

**Comment by kiyoesjh** [comment]
- 어제 한 일
1. 이슈 목록에서 선택, 전체 선택 된 이슈 상태관리
2. 이슈 상세에서 제목 부분 ui 추가

- 오늘 할 일
이슈 목록의 필터 부분 redux, redux thunk 적용 해보기

- 컨디션
  많이 늘어지는 상태입니다.. 😢

**Comment by hyewon3938** [comment]
- 어제 한 일
 1. issue Info UI 만들기 
 2. 미들웨어 redux-thunk 공부

- 오늘 할 일
 이슈 목록 필터 부분 미들웨어 적용하여 상태관리 

- 컨디션
 계속 피곤합니다 ㅠㅠ
